# Generated by Django 6.0.1 on 2026-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_product_is_available_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
